# makefile

all: dataserver client

common.o: common.h common.cpp
	g++ -g -w -std=c++14 -c common.cpp

Histogram.o: Histogram.h Histogram.cpp
	g++ -g -w -std=c++14 -c Histogram.cpp

FIFOreqchannel.o: FIFOreqchannel.h FIFOreqchannel.cpp
	g++ -g -w -std=c++14 -c FIFOreqchannel.cpp

client: client.cpp Histogram.o FIFOreqchannel.o common.o
	g++ -g -w -std=c++14 -o client client.cpp Histogram.o FIFOreqchannel.o common.o -lpthread 

dataserver: dataserver.cpp  FIFOreqchannel.o common.o
	g++ -g -w -std=c++14 -o dataserver dataserver.cpp FIFOreqchannel.o common.o -lpthread 

clean:
	rm -rf *.o fifo* dataserver client 
